spring:
  datasource:
    url: jdbc:mysql://192.168.2.120/resume?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

server:
  port: 9428
